-- AULA 1
-- CONEXÃO: psql -h 127.0.0.1. -p 5432 -U postgres

CREATE ROLE prof NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOBYPASSRLS CONNECTION LIMIT 10;
ALTER ROLE prof PASSWORD '456';
CREATE ROLE daniel LOGIN PASSWORD '123';
DROP ROLE daniel;
CREATE ROLE daniel LOGIN PASSWORD '123' IN ROLE prof;
DROP ROLE daniel;
CREATE ROLE daniel LOGIN PASSWORD '123' ROLE prof;

CREATE TABLE teste (nome varchar);
GRANT ALL ON TABLE teste TO prof;
DROP ROLE daniel;
CREATE ROLE daniel INHERIT LOGIN PASSWORD '123' IN ROLE prof;

REVOKE prof FROM daniel;